wikidata_to_gedcom:
    tree:
        method: # ["ANCESTORS", "DESCENDANTS", "FULL", "CLASSIC"]
        generation_limit: # (default 10)
        load_fathers: # true false (default true)
        load_mothers: # true false (default true)
        load_men_children: # true false (default true)
        load_women_children: # true false (default true)
    thread:
        enable: # true false (default false)
        max: # (default 10)
    export:
        format: # ["GEDCOM"]
        export_men: # true false (default true)
        export_women: # true false (default true)
    properties:
#        - SEX
#        - IS_HUMAN
#        - DATE_BIRTH
#        - DATE_DEATH
#        - GIVEN_NAME
#        - FAMILY_NAME
#        - PLACE_BIRTH
#        - PLACE_DEATH
