ConfigurationYaml.py
Configuration.py
Database.py
WikidataFetcher.py
main.py
MainModule.py
WikidataTreeGenerator.py
logger/
    Logger.py
tree_builder/
    Builder.py
    CharacterBuilder.py
    PlacerBuilder.py
    tree/
        tree_builder/
            TreeBuilder.py
            ClassicTreeBuilder.py
            AncestorsTreeBuilder.py
            DescandantsTreeBuilder.py
            FullTreeBuilder.py
        tree_generator/
            TreeGenerator.py
            CacheTreeGenerator.py
        dispatcher/
            BasicDispatcher.py
            Dispatcher.py
            ThreadedDispatcher.py
        loader/
            Loader.py
            AncestorsLoader.py
            DescendantsLoader.py
    character_fetcher/
        CacheCharacterFetcher.py
        CharacterFetcher.py
models/
    Place.py
    Name.py
    CharacterEntity.py
    Date.py
macros/
    WikidataProperties.py
export/
    Exporter.py
    JsonExporter.py
    GedcomExporter.py
entity_filler/
    EntityFiller.py
    ThreadedEntityFiller.py
    property_fillers/
        PlaceDeathFiller.py
        GivenNameFiller.py
        NameFiller.py
        FamilyNameFiller.py
        PropertyFiller.py
        PlaceBirthFiller.py
        PlaceFiller.py
    property_fetcher/
        PropertyFetcher.py
        CachePropertyFetcher.py
